package(
    default_visibility = ["//visibility:public"],
)

# cc_library(
#     name = "demo",
#     srcs = glob(["*.cc", "*.cpp"]),
#     hdrs = glob(["*.h"]),
#     deps = [
#         "@torch//:torch",
#         "@llvm-project//mlir:CAPIIR"
#     ],
# )

