package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "demo",
    srcs = glob(["*.cc"]),
    deps = [
        "@torch//:torch",
        "@llvm-project//mlir:IR"
    ],
)


