load("@hedron_compile_commands//:refresh_compile_commands.bzl", "refresh_compile_commands")

refresh_compile_commands(
    name = "refresh_compile_commands",

    targets = {
      "//degine/proto:onnx_cc_proto": "",
      "//degine/tools/degine-opt:degine-opt": "",
    },
)
